function(load_env_file filename)
  if(EXISTS ${filename})
    file(READ ${filename} file_content)
    string(REPLACE "\n" ";" file_content_list ${file_content})
    foreach(line ${file_content_list})
      if(line MATCHES "^#.*$" OR line STREQUAL "")
        continue()
      endif()
      string(REPLACE "=" ";" key_value ${line})
      list(GET key_value 0 key)
      list(GET key_value 1 value)
      set(ENV{${key}} ${value})
    endforeach()
  else()
    message(WARNING "${CMAKE_CURRENT_FUNCTION}: file `${filename}` does not exist.")
  endif()
endfunction()
